blank_issues_enabled: true

contact_links:
  - name: ğŸ’¬ Forum
    url: https://github.com/windzu/admlops/discussions
    about: Ask general usage questions and discuss with other ADMLOps community members
  - name: ğŸŒ Explore OpenMMLab
    url: https://openmmlab.com/
    about: Get know more about OpenMMLab
